data:
  token_sequence_loader:
    type: HuggingfaceTextDatasetTokenSequenceLoader
    hf_dataset_name: "monology/pile-uncopyrighted"
    sequence_length: 256
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step142000
      - name: EleutherAI/pythia-160M
        revision: step143000 # last checkpoint
    harvesting_batch_size: 1
crosscoder:
  n_latents: 4096
  k: 64
train:
  num_steps: 10_000
  batch_size: 32
  save_every_n_steps: 2500
  log_every_n_steps: 50
experiment_name: skip_trans_crosscoder_example
mlp_indices: [7]