data:
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step143000
    harvesting_batch_size: 2
  n_tokens_for_norm_estimate: 100_000
crosscoder:
  n_latents: 8192
  jumprelu:
    backprop_through_jumprelu_input: true
  initial_approx_firing_pct: 0.3 # WARNING(oli): very uncertain this is a good default!
  n_tokens_for_threshold_setting: 100_000
train:
  num_steps: 100
  batch_size: 32
  log_every_n_steps: 10
  c: 4.0
  final_lambda_s: 3.0
  lambda_p: 0.000003
experiment_name: jan_update_crosscoder_example
hookpoints: ["blocks.8.hook_resid_post"]