data:
  token_sequence_loader:
    type: HuggingFaceDatasetTokenSequenceLoader
    hf_dataset_name: monology/pile-uncopyrighted
    sequence_length: 512
  activations_harvester:
    llms:
      - name: EleutherAI/pythia-160M
        revision: step143000
    harvesting_batch_size: 2
  n_tokens_for_norm_estimate: 100_000
crosscoder:
  n_latents: 8192
  jumprelu:
    backprop_through_jumprelu_input: true
  initial_approx_firing_pct: 0.3 # WARNING(oli): very uncertain this is a good default!
  n_tokens_for_threshold_setting: 100_000
train:
  optimizer:
    type: adam
    learning_rate: 0.001
    betas: [0.0, 0.999]
  num_steps: 10_000
  batch_size: 512
  gradient_accumulation_steps_per_batch: 1
  save_every_n_steps: 99999
  log_every_n_steps: 5
  c: 4.0
  final_lambda_s: 3.0
  lambda_p: 0.000003
experiment_name: pythia-bias-test
hookpoints: ["blocks.20.hook_resid_post"]
wandb:
  project: nobias